# Site settings
title: Gabriela Reyes
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gabriela Reyes
user_description: My name is Gabriela Reyes, I am a Graduate Student in Biology at New Mexico State University.
user_title: Cellular & Molecular Biology | Microscopy | Data Analysis
email: grey1@nmsu.edu
# twitter_username: 
instagram_username: gabriela_gfp
# facebook_username: 
linkedin_username: gabriela-reyes-b066a2222/
github_username:  gabbyrey
# medium_username: 
# medium_url: 
# gplus_username: 

exclude: ['package.json', 'src' , 'node_modules']
