# Site settings
title: Gabriela Reyes
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gabriela Reyes
user_description: My name is Gabriela Reyes and I am a graduate student at New Mexico State University. Experienced researcher in cell, molecular, and developmental biology. I am interested in the intriguing mechanics of cytokinesis in sea urchin embryos. My research has led me to learn a lot at the cellular level. My work consists of imaging using various types of microscopy to view nanoscale structures in a fascinating structure called the contractile ring. Most of my time is spent in a laboratory setting but I am also learning computer programming and have some experience in Python and R programming, I obtained a Google Data Analytics certification. In the future I’d love to apply my experiences in the field of cancer research. 
user_title: Cellular & Molecular Biology | Microscopy | Data Analysis
email: grey1@nmsu.edu
# twitter_username: 
instagram_username: gabriela_gfp
# facebook_username: 
linkedin_username: gabriela-reyes-b066a2222/
github_username:  gabbyrey
# medium_username: 
# medium_url: 
# gplus_username: 

exclude: ['package.json', 'src' , 'node_modules']
