# Site settings
title: Gabriela Reyes
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gabriela Reyes
user_description: Coming soon...
user_title: Microscopy | Cell Biology | Molecular Biology
email: jorge_galarza_1@outlook.com
# twitter_username: lorem_ipsum
# instagram_username: 
# facebook_username: 
linkedin_username: gabriela-reyes-b066a2222/
github_username:  gabbyrey
# medium_username: 
# medium_url: 
# gplus_username: 

exclude: ['package.json', 'src' , 'node_modules']
